FROM ubuntu:trusty
MAINTAINER Thirumalai Veerasamy <techy@thiru.in>

# Install packages
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -y update && apt-get -y upgrade

RUN ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
